### ISSUE TITLE
IP whitelisting

### ISSUE THREAD

**Issue by huevoncito** [MicrosoftDocs/Viva#490]
This documentation provides no guidance about which IP ranges to whitelist. Any secured database will need to know which IP range Viva is using.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8cbf67a3-197a-f620-43f2-8cb5806817dd
* Version Independent ID: 8cbf67a3-197a-f620-43f2-8cb5806817dd
* Content: [PostgreSQL integration](https://learn.microsoft.com/en-us/viva/goals/postgresql-integration)
* Content Source: [Viva/goals/postgresql-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/postgresql-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by dariomws** [comment]
Hi @huevoncito, thank you for your feedback.

These IP addresses should be included here but not yet:
https://learn.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges

Because all Microsoft 365 endpoints data displayed in this article is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data.

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.

@RaSanders-MSFT, maybe you can provide additional information. Thanks!
