### ISSUE TITLE
IP Range for MS SQL?

### ISSUE THREAD

**Issue by arlogilbert** [MicrosoftDocs/Viva#526]
Best practices are that database servers should not be available to the entire Internet, so we have enabled the MS SQL firewall and we allowlist IPs that can connect.

What are the IP ranges that Viva Goals would use when connecting to our database?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7074f9af-0e5c-279a-8ea1-c2d1efc5e37d
* Version Independent ID: 7074f9af-0e5c-279a-8ea1-c2d1efc5e37d
* Content: [Microsoft SQL Server integration](https://learn.microsoft.com/en-us/viva/goals/ms-sql-server-integration)
* Content Source: [Viva/goals/ms-sql-server-integration.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/goals/ms-sql-server-integration.md)
* Service: **viva**
* Sub-service: **viva-goals**
* GitHub Login: @RaSanders-MSFT
* Microsoft Alias: **rasanders**

**Comment by dariomws** [comment]
Hi @arlogilbert, thank you for your feedback.

These IP addresses should be included here but not yet:
https://learn.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges

Because all Microsoft 365 endpoints data displayed in this article is autogenerated by the Microsoft 365 endpoints web service, the content team cannot resolve issues directly related to this data.

We recommend that you contact your organization’s TAM (Technical Account Manager) to escalate your inquiry to the engineering team associated with the endpoint in question. If you do not have a TAM assigned to your organization, please contact Microsoft Support.

@RaSanders-MSFT, maybe you can provide additional information. Thanks!

**Comment by dariomws** [comment]
Similar to https://github.com/MicrosoftDocs/Viva/issues/490.
