### ISSUE TITLE
Please make this page available in Spanish (ES-ES)

### ISSUE THREAD

**Issue by soyalejolopez** [MicrosoftDocs/Viva#533]
🚨 Looks like you arrived from the internal review site 
🚨 Do not enter Microsoft confidential information here

Please make this page available in Spanish (ES-ES)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7a667d12-913e-e88d-f4a4-953c60814616
* Version Independent ID: 909d3d3b-25fd-5e7c-6da5-c64be452462e
* Content: [Viva Insights insights for managers](https://review.learn.microsoft.com/en-us/viva/insights/use/pm-home?branch=main)
* Content Source: [Viva/insights/use/pm-home.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/insights/use/pm-home.md)
* Service: **viva**
* Sub-service: **viva-insights**
* GitHub Login: @madehmer
* Microsoft Alias: **helayne**

**Comment by tiburd** [comment]
Thank you for submitting this localization issue.

I submitted a translation bug: [274380](https://dev.azure.com/GlobalCollaborationService/Global%20Collaboration%20Service%20Project/_workitems/edit/274380)

I'm closing this issue because the Global Services team will handle it from here.

Also, if you a Microsoft employee, please complete your account setup so that your GitHub and Microsoft accounts are connected:
- [Set up your accounts](https://review.docs.microsoft.com/en-us/office-authoring-guide/contribute-get-started-setup-github-ro?branch=main)

**Comment by soyalejolopez** [comment]
Great, thank you Tina!
