### ISSUE TITLE
Viva Engage License requirements for Champains

### ISSUE THREAD

**Issue by Jvasil** [MicrosoftDocs/Viva#547]
Can you please specify whiceViva Engage license sku is needed for users to be able to see, post to, and hashtag reference Viva Engage Campaigns? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4fb9d2aa-e703-ca77-fd4e-9303b38dedb4
* Version Independent ID: 4fb9d2aa-e703-ca77-fd4e-9303b38dedb4
* Content: [Manage and set up campaigns in Microsoft Viva Engage](https://learn.microsoft.com/en-us/viva/engage/campaigns)
* Content Source: [Viva/engage/campaigns.md](https://github.com/MicrosoftDocs/OfficeDocs-WorkplaceAnalytics/blob/public/Viva/engage/campaigns.md)
* Service: **viva**
* Sub-service: **viva-engage**
* GitHub Login: @mamiepjohnson
* Microsoft Alias: **mamiejohnson**

**Comment by mamiepjohnson** [comment]
Hi! Thanks for this message – to provide a bit more context, the SKU details for premium features are covered in the Key admin roles and permissions in Viva Engage<https://learn.microsoft.com/en-us/viva/engage/eac-key-admin-roles-permissions> article and the Set up the Engage admin center<https://learn.microsoft.com/en-us/viva/engage/eac-get-started>
Article on the admin side. Additionally, in our end user documentation for campaigns<https://support.microsoft.com/en-us/topic/campaigns-in-viva-engage-d7b05128-f80b-4c16-b561-3ddce518eb14>, we made sure to mention which license is required to participate in campaigns!

Thus, I don’t believe there’s a need to reiterate this information since it already is detailed throughout both our admin and end user documentation. Hope this helps add context!

Best,
Mamie

From: Jvasil ***@***.***>
Date: Tuesday, March 7, 2023 at 6:05 AM
To: MicrosoftDocs/Viva ***@***.***>
Cc: Mamie Johnson ***@***.***>, Mention ***@***.***>
Subject: [MicrosoftDocs/Viva] Viva Engage License requirements for Champains (Issue #547)

Can you please specify whiceViva Engage license sku is needed for users to be able to see, post to, and hashtag reference Viva Engage Campaigns?

________________________________
Document Details

⚠ Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

  *   ID: 4fb9d2aa-e703-ca77-fd4e-9303b38dedb4
  *   Version Independent ID: 4fb9d2aa-e703-ca77-fd4e-9303b38dedb4
  *   Content: Manage and set up campaigns in Microsoft Viva Engage<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fviva%2Fengage%2Fcampaigns&data=05%7C01%7Cmamiejohnson%40microsoft.com%7C5034e93fb56d46e5b8ee08db1f14f655%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638137947120029148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F9zPr3v7I1vbe9UGLIv8V2BKR2ESsrxQaYbEwI02KA8%3D&reserved=0>
  *   Content Source: Viva/engage/campaigns.md<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2FOfficeDocs-WorkplaceAnalytics%2Fblob%2Fpublic%2FViva%2Fengage%2Fcampaigns.md&data=05%7C01%7Cmamiejohnson%40microsoft.com%7C5034e93fb56d46e5b8ee08db1f14f655%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638137947120029148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=E1QZj%2BdMz3JNku2wcMEauh5pumQvefsZR%2F%2B9ihxVHiE%3D&reserved=0>
  *   Service: viva
  *   Sub-service: viva-engage
  *   GitHub Login: @mamiepjohnson<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmamiepjohnson&data=05%7C01%7Cmamiejohnson%40microsoft.com%7C5034e93fb56d46e5b8ee08db1f14f655%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638137947120029148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6gyxgyipRphqEUTfkWwOawQkpJ3WkvwpRTQEv%2B20UZc%3D&reserved=0>
  *   Microsoft Alias: mamiejohnson

**Comment by scanum** [comment]
We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
